# Generated by Django 5.2.4 on 2025-08-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='tags',
            new_name='tag',
        ),
    ]
