# Generated by Django 5.2.4 on 2025-08-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_tags_tracker_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='platform',
            field=models.CharField(choices=[('LeetCode', 'LeetCode'), ('HackerRank', 'HackerRank'), ('CodeChef', 'CodeChef'), ('GeeksforGeeks', 'GeeksforGeeks'), ('Codeforces', 'Codeforces'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
