# Generated by Django 5.2.4 on 2025-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tracker_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
