# Generated by Django 5.2.4 on 2025-08-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tracker_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='mquotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
            ],
        ),
    ]
