# Generated by Django 5.2.4 on 2025-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_mquotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
