# Generated by Django 5.2.4 on 2025-08-14 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_tracker_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tags'),
        ),
    ]
