# Generated by Django 5.2.4 on 2025-08-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_tracker_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
